### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by svkazakov** [fenderglass/Ragout#12]
I run ragout on a small plasmid sequence, but got IndexError:

command: ragout.py plasmid_1.rcp --outdir plasmid_1 -t 6 --debug

file plasmid_1.rcp:
.references = gr-8,pds
.target = plasmid

plasmid.fasta = chr1_1/chr_unplaced.fasta
gr-8.fasta = references/Bacillus_pumilus_GR-8.plasmid.fa
pds.fasta = references/Bacillus_pumilus_PDSLzg-1.plasmid.fa

ragout.log:
[14:23:25] INFO: Starting Ragout v1.2
[14:23:26] INFO: Synteny block scale set to 'small'
[14:23:26] INFO: Running Sibelia with block size 5000
[14:23:26] INFO: Running Sibelia with block size 500
[14:23:26] INFO: Running Sibelia with block size 100
[14:23:26] INFO: Inferring phylogeny from synteny blocks data
[14:23:26] DEBUG: Reading permutation file
[14:23:26] DEBUG: "gr-8" synteny blocks coverage: 61.05%
[14:23:26] DEBUG: "pds" synteny blocks coverage: 99.94%
[14:23:26] DEBUG: "plasmid" synteny blocks coverage: 21.72%
[14:23:26] WARNING: "plasmid" synteny blocks coverage (21.72%) is too low -- results can be inaccurate. Possible reasons are: 

1. Genome is too distant from others
2. Synteny block parameters are chosen incorrectly

Try to change synteny blocks paramsters or remove this genome from the comparison
[14:23:26] DEBUG: Read 2 reference sequences
[14:23:26] DEBUG: Read 4 target sequences
[14:23:26] DEBUG: 0 target sequences left after indel filtering
[14:23:26] DEBUG: 0 target sequences left after repeat filtering
Traceback (most recent call last):
  File "/home/svkazakov/work/genome/tools/Ragout/ragout.py", line 32, in <module>
    sys.exit(main())
  File "/home/svkazakov/work/genome/tools/Ragout/ragout/main.py", line 268, in main
    return run_ragout(args)
  File "/home/svkazakov/work/genome/tools/Ragout/ragout/main.py", line 95, in run_ragout
    run_unsafe(args)
  File "/home/svkazakov/work/genome/tools/Ragout/ragout/main.py", line 180, in run_unsafe
    phylo_perm_file)
  File "/home/svkazakov/work/genome/tools/Ragout/ragout/main.py", line 132, in get_phylogeny_and_naming_ref
    phylogeny = Phylogeny.from_permutations(perm_cont)
  File "/home/svkazakov/work/genome/tools/Ragout/ragout/phylogeny/phylogeny.py", line 38, in from_permutations
    return phylo(ti.build())
  File "/home/svkazakov/work/genome/tools/Ragout/ragout/phylogeny/inferer.py", line 116, in build
    tree = list(taxas)[0]
IndexError: list index out of range

**Comment by fenderglass** [comment]
Hi,

It seems that there were no synteny blocks found in the target genome, which are non-repetitive and shared across all genomes - this led to an unexpected error, as these blocks are necessary for the first Ragout iteration. You may try to leave only one closest reference and rerun the assembly. 

However, it also seems that the target genome is quite divergent from the references (20% synteny blocks coverage, we usually require 70%+), so most likely this set of references will not work for your target genome - you might need less distant genomes.
