### ISSUE TITLE
Error - IndexError: list index out of range

### ISSUE THREAD

**Issue by BrGAl** [fenderglass/Ragout#14]
Hello, I've successfully used ragout on a set of draft assemblies to obtain pseudo-molecules using a single reference. The draft assemblies are for strains of the same species, low divergence expected (~97-99%)  but genomic rearrangements might potentially be there. For two strains only I've encountered this error:

Traceback (most recent call last):
  File "/software/shared/apps/x86_64/ragout/1.2//ragout.py", line 32, in <module>
    sys.exit(main())
  File "/shared/clssoft/apps/x86_64/ragout/1.2/ragout/main.py", line 268, in main
    return run_ragout(args)
  File "/shared/clssoft/apps/x86_64/ragout/1.2/ragout/main.py", line 95, in run_ragout
    run_unsafe(args)
  File "/shared/clssoft/apps/x86_64/ragout/1.2/ragout/main.py", line 212, in run_unsafe
    all_breaks, stage.rearrange)
  File "/shared/clssoft/apps/x86_64/ragout/1.2/ragout/scaffolder/merge_iters.py", line 42, in merge_scaffolds
    projector = RearrangementProjector(big_updated, small_updated, True)
  File "/shared/clssoft/apps/x86_64/ragout/1.2/ragout/scaffolder/merge_iters.py", line 147, in __init__
    self._build_bp_graph()
  File "/shared/clssoft/apps/x86_64/ragout/1.2/ragout/scaffolder/merge_iters.py", line 248, in _build_bp_graph
    bp_graph.add_edge(scf.contigs[0].left_end(),
IndexError: list index out of range

And the ragout.log:

root: INFO: Starting Ragout v1.2
root: INFO: Running Sibelia with block size 5000
root: INFO: Running Sibelia with block size 500
root: INFO: Running Sibelia with block size 100
root: INFO: Inferring phylogeny from synteny blocks data
root: DEBUG: Reading permutation file
root: DEBUG: "reference" synteny blocks coverage: 94.76%
root: DEBUG: "strainX" synteny blocks coverage: 98.74%
root: DEBUG: Read 40 reference sequences
root: DEBUG: Read 501 target sequences
root: DEBUG: 492 target sequences left after indel filtering
root: DEBUG: 461 target sequences left after repeat filtering
root: DEBUG: Branch lengths: [39.5, 39.5], mu = 0.0253164556962
root: INFO: (strainX : 39.5, reference : 39.5)
root: INFO: 'reference' is chosen as a naming reference
root: INFO: Processing permutation files
root: DEBUG: Reading permutation file
root: DEBUG: "reference" synteny blocks coverage: 90.08%
root: DEBUG: "strainX" synteny blocks coverage: 97.44%
root: DEBUG: Read 35 reference sequences
root: DEBUG: Read 365 target sequences
root: DEBUG: 365 target sequences left after indel filtering
root: DEBUG: 364 target sequences left after repeat filtering
root: DEBUG: Built breakpoint graph with 1302 nodes
root: DEBUG: Reading permutation file
root: DEBUG: "reference" synteny blocks coverage: 94.56%
root: DEBUG: "strainX" synteny blocks coverage: 98.82%
root: DEBUG: Read 40 reference sequences
root: DEBUG: Read 459 target sequences
root: DEBUG: 459 target sequences left after indel filtering
root: DEBUG: 449 target sequences left after repeat filtering
root: DEBUG: Built breakpoint graph with 1694 nodes
root: DEBUG: Reading permutation file
root: DEBUG: "reference" synteny blocks coverage: 94.76%
root: DEBUG: "strainX" synteny blocks coverage: 98.74%
root: DEBUG: Read 40 reference sequences
root: DEBUG: Read 501 target sequences
root: DEBUG: 501 target sequences left after indel filtering
root: DEBUG: 461 target sequences left after repeat filtering
root: DEBUG: Built breakpoint graph with 4296 nodes
root: DEBUG: Reading permutation file
root: DEBUG: "reference" synteny blocks coverage: 94.76%
root: DEBUG: "strainX" synteny blocks coverage: 98.74%
root: DEBUG: Read 40 reference sequences
root: DEBUG: Read 501 target sequences
root: DEBUG: 492 target sequences left after indel filtering
root: DEBUG: 461 target sequences left after repeat filtering
root: DEBUG: Built breakpoint graph with 4296 nodes
root: DEBUG: Detecting chimeric adjacencies
root: INFO: Stage "5000"
root: DEBUG: Chimera Detector: 19 cuts made in 17 sequences
root: DEBUG: Lost 0 blocks
root: DEBUG: Built breakpoint graph with 1302 nodes
root: INFO: Inferring missing adjacencies
root: DEBUG: Found 651 connected components
root: DEBUG: Inferred 383 adjacencies
root: DEBUG: 0 orphaned nodes
root: DEBUG: 0 guessed edges
root: DEBUG: 268 trimmed edges
root: INFO: Building scaffolds
root: DEBUG: 383 contigs were joined into 35 scaffolds
root: INFO: Stage "500"
root: DEBUG: Chimera Detector: 34 cuts made in 30 sequences
root: DEBUG: Lost 0 blocks
root: DEBUG: Built breakpoint graph with 1694 nodes
root: INFO: Inferring missing adjacencies
root: DEBUG: Found 843 connected components
root: DEBUG: Inferred 483 adjacencies
root: DEBUG: 0 orphaned nodes
root: DEBUG: 0 guessed edges
root: DEBUG: 364 trimmed edges
root: INFO: Building scaffolds
root: DEBUG: 483 contigs were joined into 36 scaffolds
root: DEBUG: Chimera Detector: 42 cuts made in 30 sequences
root: DEBUG: Lost 1 blocks
root: INFO: Merging two iterations
root: DEBUG: Lost: [strainX, scaffold157|size49338, [338], b:24504, e:49652]
root: DEBUG: Lost: [strainX, scaffold106|size71757, [572], b:0, e:14083]
root: DEBUG: Lost: [strainX, scaffold193|size37349, [-231], b:30361, e:37303]
root: DEBUG: Lost: [strainX, scaffold24|size164809, [-295], b:151430, e:164768]
root: DEBUG: Lost: [strainX, scaffold21|size166520, [362], b:158889, e:166525]
root: DEBUG: Lost: [strainX, scaffold106|size71757, [790], b:14200, e:71736]

I do not expect these two strains to be very different from the rest of the strains, I've also aligned the contigs to the reference using MUMmer  and everything looks okay. 
Any comments and suggestions are welcome and thanks for your time!

**Comment by fenderglass** [comment]
Hi,
Thank you for the feedback!

Definitely looks like a bug. Please try the new version from the devel branch and see if it fixes the problem. If you will have troubles with compilation, you also can reuse the binaries from your current version (but I recommend you to update it to 2.0 though).

Best,
Mikhail

**Comment by BrGAl** [comment]
Hello Mikhail,

thanks for your reply. Indeed the update to ragout 2.0 solved the problem
for all samples except one. I am attaching the ragout log and the error:

[15:09:23] root: INFO: Starting Ragout v2.0
[15:09:24] root: INFO: Running Sibelia with block size 5000
[15:17:11] root: INFO: Running Sibelia with block size 500
[15:25:09] root: INFO: Running Sibelia with block size 100
[15:32:56] root: INFO: Inferring phylogeny from synteny blocks data
[15:32:56] root: DEBUG: Reading permutation file
[15:32:56] root: DEBUG: "referenceNoIUPAC" synteny blocks coverage: 95.21%
[15:32:56] root: DEBUG: "strain" synteny blocks coverage: 98.83%
[15:32:56] root: DEBUG: Read 40 reference sequences
[15:32:56] root: DEBUG: Read 450 target sequences
[15:32:57] root: DEBUG: 445 target sequences left after indel filtering
[15:32:57] root: DEBUG: 427 target sequences left after repeat filtering
[15:32:57] root: DEBUG: Branch lengths: [61.5, 61.5], mu = 0.0162601626016
[15:32:57] root: INFO: (strain : 61.5, referenceNoIUPAC : 61.5)
[15:32:57] root: INFO: 'referenceNoIUPAC' is chosen as a naming reference
[15:32:57] root: INFO: Processing permutation files
[15:32:57] root: DEBUG: Reading permutation file
[15:32:57] root: DEBUG: "referenceNoIUPAC" synteny blocks coverage: 90.75%
[15:32:57] root: DEBUG: "strain" synteny blocks coverage: 97.66%
[15:32:57] root: DEBUG: Read 35 reference sequences
[15:32:57] root: DEBUG: Read 375 target sequences
[15:32:57] root: DEBUG: 375 target sequences left after indel filtering
[15:32:57] root: DEBUG: 372 target sequences left after repeat filtering
[15:32:57] root: DEBUG: Built breakpoint graph with 1256 nodes
[15:32:57] root: DEBUG: Reading permutation file
[15:32:57] root: DEBUG: "referenceNoIUPAC" synteny blocks coverage: 95.06%
[15:32:57] root: DEBUG: "strain" synteny blocks coverage: 98.92%
[15:32:57] root: DEBUG: Read 40 reference sequences
[15:32:57] root: DEBUG: Read 432 target sequences
[15:32:57] root: DEBUG: 432 target sequences left after indel filtering
[15:32:58] root: DEBUG: 419 target sequences left after repeat filtering
[15:32:58] root: DEBUG: Built breakpoint graph with 1580 nodes
[15:32:58] root: DEBUG: Reading permutation file
[15:32:58] root: DEBUG: "referenceNoIUPAC" synteny blocks coverage: 95.21%
[15:32:58] root: DEBUG: "strain" synteny blocks coverage: 98.83%
[15:32:58] root: DEBUG: Read 40 reference sequences
[15:32:58] root: DEBUG: Read 450 target sequences
[15:32:58] root: DEBUG: 450 target sequences left after indel filtering
[15:32:59] root: DEBUG: 427 target sequences left after repeat filtering
[15:32:59] root: DEBUG: Built breakpoint graph with 3972 nodes
[15:32:59] root: DEBUG: Reading permutation file
[15:32:59] root: DEBUG: "referenceNoIUPAC" synteny blocks coverage: 95.21%
[15:32:59] root: DEBUG: "strain" synteny blocks coverage: 98.83%
[15:32:59] root: DEBUG: Read 40 reference sequences
[15:32:59] root: DEBUG: Read 450 target sequences
[15:32:59] root: DEBUG: 445 target sequences left after indel filtering
[15:32:59] root: INFO: Resolving repeats
[15:32:59] root: DEBUG: Unique repeat blocks: 997
[15:32:59] root: DEBUG: Purely repetitive sequences: 18
[15:33:02] root: DEBUG: Repetitive sequences with matches: 14
[15:33:02] root: DEBUG: Unique matches: 1735
[15:33:02] root: DEBUG: Repetitive matches: 351
[15:33:02] root: DEBUG: Resolved 171 unique repeat instances
[15:33:02] root: DEBUG: Saved sequences: 12
[15:33:02] root: DEBUG: Added 51 extra contigs
[15:33:03] root: DEBUG: 478 target sequences left after repeat filtering
[15:33:03] root: DEBUG: Built breakpoint graph with 4314 nodes
[15:33:03] root: INFO: Reading contigs file
[15:33:04] root: DEBUG: Detecting chimeric adjacencies
[15:33:04] root: DEBUG: Checking 256 target adjacencies
[15:33:04] root: DEBUG: Found 57 target-specific adjacencies, 57 broken as
chimeric
[15:33:04] root: DEBUG: Checking 371 target adjacencies
[15:33:04] root: DEBUG: Found 100 target-specific adjacencies, 95 broken as
chimeric
[15:33:04] root: DEBUG: Checking 1559 target adjacencies
[15:33:04] root: DEBUG: Found 123 target-specific adjacencies, 111 broken
as chimeric
[15:33:05] root: DEBUG: Checking 1679 target adjacencies
[15:33:05] root: DEBUG: Found 123 target-specific adjacencies, 111 broken
as chimeric
[15:33:05] root: INFO: Stage "5000"
[15:33:05] root: INFO: Removing chimeric adjacencies
[15:33:05] root: DEBUG: Chimera Detector: 57 cuts made in 49 sequences
[15:33:05] root: DEBUG: Built breakpoint graph with 1256 nodes
[15:33:05] root: INFO: Inferring missing adjacencies
[15:33:06] root: DEBUG: Found 628 connected components
[15:33:06] root: DEBUG: Inferred 429 adjacencies
[15:33:06] root: DEBUG: 0 orphaned nodes
[15:33:06] root: DEBUG: 0 guessed edges
[15:33:06] root: DEBUG: 199 trimmed edges
[15:33:06] root: DEBUG: Building scaffolds
[15:33:06] root: DEBUG: 429 contigs were joined into 35 scaffolds
[15:33:06] root: DEBUG: Target-specific adjacencies in scaffolds: 0
[15:33:06] root: INFO: Stage "500"
[15:33:06] root: INFO: Removing chimeric adjacencies
[15:33:06] root: DEBUG: Chimera Detector: 95 cuts made in 71 sequences
[15:33:06] root: DEBUG: Built breakpoint graph with 1580 nodes
[15:33:06] root: INFO: Inferring missing adjacencies
[15:33:06] root: DEBUG: Found 787 connected components
[15:33:07] root: DEBUG: Inferred 514 adjacencies
[15:33:07] root: DEBUG: 0 orphaned nodes
[15:33:07] root: DEBUG: 0 guessed edges
[15:33:07] root: DEBUG: 276 trimmed edges
[15:33:07] root: DEBUG: Building scaffolds
[15:33:07] root: DEBUG: 514 contigs were joined into 37 scaffolds
[15:33:07] root: INFO: Removing chimeric adjacencies
[15:33:07] root: DEBUG: Chimera Detector: 122 cuts made in 71 sequences
[15:33:07] root: INFO: Merging two iterations
[15:33:07] root: DEBUG: Lost: [strain, scaffold31|size140780, [325],
b:100433, e:141062]
[15:33:07] root: DEBUG: Lost: [strain, scaffold23|size156990, [-228],
b:147681, e:157063]
[15:33:07] root: DEBUG: Lost: [strain, scaffold152|size51647, [162],
b:31611, e:51647]
[15:33:07] root: DEBUG: Lost: [strain, scaffold143|size57036, [363],
b:23527, e:57036]
[15:33:07] root: DEBUG: Lost: [strain, scaffold187|size39401, [-260],
b:33744, e:39406]
[15:33:07] root: DEBUG: Lost: [strain, scaffold242|size27138, [500],
b:7198, e:27123]
[15:33:07] root: DEBUG: Lost: [strain, scaffold3|size288318, [412],
b:194733, e:288341]
[15:33:07] root: DEBUG: Lost: [strain, scaffold69|size99623, [106], b:0,
e:5604]
[15:33:07] root: DEBUG: Lost: [strain, scaffold228|size29891, [594], b:0,
e:24699]
[15:33:07] root: DEBUG: Lost: [strain, scaffold46|size124175, [422],
b:61044, e:124175]
[15:33:07] root: DEBUG: Lost: [strain, scaffold51|size116260, [326],
b:73506, e:116260]
[15:33:07] root: DEBUG: Lost: [strain, scaffold75|size94369, [410],
b:86733, e:94369]
[15:33:07] root: DEBUG: Lost: [strain, scaffold23|size156990, [299],
b:147181, e:157063]
[15:33:07] root: DEBUG: Lost: [strain, scaffold96|size80352, [756],
b:79562, e:80540]
[15:33:07] root: DEBUG: Lost: [strain, scaffold148|size54851, [700],
b:12611, e:54851]


[15:09:23] INFO: Starting Ragout v2.0
[15:09:24] INFO: Running Sibelia with block size 5000
[15:17:11] INFO: Running Sibelia with block size 500
[15:25:09] INFO: Running Sibelia with block size 100
[15:32:56] INFO: Inferring phylogeny from synteny blocks data
[15:32:57] INFO: (strain : 61.5, referenceNoIUPAC : 61.5)
[15:32:57] INFO: 'referenceNoIUPAC' is chosen as a naming reference
[15:32:57] INFO: Processing permutation files
[15:32:59] INFO: Resolving repeats
[15:33:03] INFO: Reading contigs file
[15:33:05] INFO: Stage "5000"
[15:33:05] INFO: Removing chimeric adjacencies
[15:33:05] INFO: Inferring missing adjacencies
[15:33:06] INFO: Stage "500"
[15:33:06] INFO: Removing chimeric adjacencies
[15:33:06] INFO: Inferring missing adjacencies
[15:33:07] INFO: Removing chimeric adjacencies
[15:33:07] INFO: Merging two iterations
Traceback (most recent call last):
  File "/software/shared/apps/x86_64/ragout/2.0//ragout.py", line 32, in
<module>
    sys.exit(main())
  File "/shared/clssoft/apps/x86_64/ragout/2.0/ragout/main.py", line 286,
in main
    _run_ragout(args)
  File "/shared/clssoft/apps/x86_64/ragout/2.0/ragout/main.py", line 219,
in _run_ragout
    stage.rearrange)
  File
"/shared/clssoft/apps/x86_64/ragout/2.0/ragout/scaffolder/merge_iters.py",
line 42, in merge_scaffolds
    projector = RearrangementProjector(big_updated, small_updated, True)
  File
"/shared/clssoft/apps/x86_64/ragout/2.0/ragout/scaffolder/merge_iters.py",
line 166, in __init__
    self._build_bp_graph()
  File
"/shared/clssoft/apps/x86_64/ragout/2.0/ragout/scaffolder/merge_iters.py",
line 267, in _build_bp_graph
    bp_graph.add_edge(scf.contigs[0].left_end(),
IndexError: list index out of range


Do you have any idea  what is causing the error?
Thanks again!


2016-12-20 20:47 GMT+01:00 Mikhail Kolmogorov <notifications@github.com>:

**Comment by fenderglass** [comment]
Hi,

It looks like the same error is happening. Just to make sure, did you download 2.0 version from the releases page, or did you pull the latest version from the "devel" branch from github? The latter one should contain a fix for this specific problem.

So, the first thing to do it to make sure you are using the latest version. To download the latest version, go to the project page (https://github.com/fenderglass/Ragout), click on "clone or download" button and choose "download zip" (I recently merged devel and master branches). You will need to compile the binaries from source, but if you will have any troubles you can reuse ones from the 2.0 release you are currently using.

Let me know if you have any issues with that,
Mikhail

**Comment by BrGAl** [comment]
Hello,

it worked perfectly!
Thank you very much

Brigida

2017-01-19 20:27 GMT+01:00 Mikhail Kolmogorov <notifications@github.com>:
