### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by kingcohn1** [fenderglass/Ragout#16]
Hello and thank you for developing this useful program. I am attempting to map ~500Mega base,  ~200K contig draft assembly to a ~640Mega base, ~20K scaffold reference assembly with the following input and error. Please let me know what I can do to resolve this and thank you for your consideration. 

``` 
~/Desktop/ragout-2.0-linux-x86_64$ ./ragout.py cp3.rcp --outdir examples/CP3/out/ --refine
Traceback (most recent call last):
  File "./ragout.py", line 32, in <module>
    sys.exit(main())
  File "/home/molecularecology/Desktop/ragout-2.0-linux-x86_64/ragout/main.py", line 286, in main
    _run_ragout(args)
  File "/home/molecularecology/Desktop/ragout-2.0-linux-x86_64/ragout/main.py", line 150, in _run_ragout
    os.mkdir(args.out_dir)
OSError: [Errno 2] No such file or directory: 'examples/CP3/out/'
molecularecology@molecular-ecology:~/Desktop/ragout-2.0-linux-x86_64$ ./ragout.py cp3.rcp --outdir examples/CP3/ --refine
[11:59:03] INFO: Starting Ragout v2.0
Traceback (most recent call last):
  File "./ragout.py", line 32, in <module>
    sys.exit(main())
  File "/home/molecularecology/Desktop/ragout-2.0-linux-x86_64/ragout/main.py", line 286, in main
    _run_ragout(args)
  File "/home/molecularecology/Desktop/ragout-2.0-linux-x86_64/ragout/main.py", line 165, in _run_ragout
    recipe = parse_ragout_recipe(args.recipe)
  File "/home/molecularecology/Desktop/ragout-2.0-linux-x86_64/ragout/parsers/recipe_parser.py", line 53, in parse_ragout_recipe
    (obj, param_name), value = m.group(1).split("."), m.group(2)
ValueError: too many values to unpack
```

**Comment by fenderglass** [comment]
Hello,

Most likely the genome names contain dots, could you remove them and try again? This was fixed in the development version, but have not made it to the latest release yet - sorry about that.

Also, it could be that your genomes (1 GB in total) are too large for Sibelia, so you might consider alignment with progressiveCactus instead.

**Comment by kingcohn1** [comment]
Hello and thanks for your quick response! The file names have dots before the filetype as: ```Ldec_redundans_on_alpaths_contigs_genome.fasta ``` and   ``` scaffolds.fasta``` are these the ones I should remove? I'm also running into errors when installing progressiveCactus:

```
" /home/molecularecolo...ols-0.6c11-py2.7.egg failed with error code 1
Makefile:19: recipe for target 'virtPyRule' failed
make[1]: *** [virtPyRule] Error 1
make[1]: Leaving directory '/home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules'
Makefile:10: recipe for target 'all' failed
make: *** [all] Error 2
```
Did I fail to set the environment properly? Thank you, this is all relatively new to me.

**Comment by kspham** [comment]
On Sat, Jan 7, 2017 at 7:11 PM, kingcohn1 <notifications@github.com> wrote:

> Hello and thanks for your quick response! The file names have dots before
> the filetype as: Ldec_redundans_on_alpaths_contigs_genome.fasta and
> scaffolds.fasta are these the ones I should remove? I'm also running into
> errors when installing progressiveCactus:
>
Please post your cactus issue here:
https://github.com/glennhickey/progressiveCactus/issues
Will be good to mention the purpose you need to run progressiveCactus.
Son.

**Comment by kingcohn1** [comment]
Ok, will do. But if you have any advice I'd appreciate it as my exact issue has been posted in the past, with no resolution (https://github.com/glennhickey/progressiveCactus/issues/44)

**Comment by kingcohn1** [comment]
are there other tools I ragout can call upon like mummer?

**Comment by fenderglass** [comment]
Dots should be removed from genome names in the recipe file. For example, 

`.reference = something.something_else`

should become 

`.reference = something`

As Son said, it is better to write to the maintainers of progressiveCactus. If you can post full make log (not only the last lines), we also can take a look.

Currently, progressiveCactus is an only option because of special properties of the alignment it outputs - it is non-overlapping and has correct positional homology assignments.

**Comment by kingcohn1** [comment]
Great, ok thank you very much. I don't have the complete log on this
device, but will comment on this issue and the one I started at cactus with
it asap.

**Comment by kingcohn1** [comment]
As you suggested I removed the dots from the .rcp file, and received the error from the top of this issue. Just to be sure, here is the complete error for progressiveCactus
```
/progressiveCactus$ make
cd submodules && make all
make[1]: Entering directory '/home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules'
rm -f /home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules/../environment
python /home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules/virtualenv/virtualenv.py /home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/python
New python executable in /home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/python/bin/python
Installing setuptools...................................
  Complete output from command /home/molecularecolo...us/python/bin/python -c "#!python
\"\"\"Bootstra...sys.argv[1:])






" /home/molecularecolo...ols-0.6c11-py2.7.egg:
  Traceback (most recent call last):
  File "<string>", line 279, in <module>
  File "<string>", line 240, in main
  File "/home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules/virtualenv/virtualenv_support/setuptools-0.6c11-py2.7.egg/setuptools/command/easy_install.py", line 1712, in main
  File "/home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules/virtualenv/virtualenv_support/setuptools-0.6c11-py2.7.egg/setuptools/command/easy_install.py", line 1700, in with_ei_usage
  File "/home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules/virtualenv/virtualenv_support/setuptools-0.6c11-py2.7.egg/setuptools/command/easy_install.py", line 1716, in <lambda>
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 971, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules/virtualenv/virtualenv_support/setuptools-0.6c11-py2.7.egg/setuptools/command/easy_install.py", line 125, in finalize_options
  File "/home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules/virtualenv/virtualenv_support/setuptools-0.6c11-py2.7.egg/setuptools/command/easy_install.py", line 1121, in _expand
  File "/usr/lib/python2.7/distutils/cmd.py", line 312, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules/virtualenv/virtualenv_support/setuptools-0.6c11-py2.7.egg/setuptools/command/install.py", line 32, in finalize_options
  File "/usr/lib/python2.7/distutils/command/install.py", line 321, in finalize_options
    (prefix, exec_prefix) = get_config_vars('prefix', 'exec_prefix')
  File "/home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/python/lib/python2.7/distutils/__init__.py", line 92, in sysconfig_get_config_vars
    real_vars = old_get_config_vars(*args)
  File "/usr/lib/python2.7/distutils/sysconfig.py", line 513, in get_config_vars
    func()
  File "/usr/lib/python2.7/distutils/sysconfig.py", line 457, in _init_posix
    from _sysconfigdata import build_time_vars
  File "/usr/lib/python2.7/_sysconfigdata.py", line 6, in <module>
    from _sysconfigdata_nd import *
ImportError: No module named _sysconfigdata_nd
----------------------------------------
...Installing setuptools...done.
Traceback (most recent call last):
  File "/home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules/virtualenv/virtualenv.py", line 2471, in <module>
    main()
  File "/home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules/virtualenv/virtualenv.py", line 942, in main
    never_download=options.never_download)
  File "/home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules/virtualenv/virtualenv.py", line 1052, in create_environment
    search_dirs=search_dirs, never_download=never_download)
  File "/home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules/virtualenv/virtualenv.py", line 599, in install_setuptools
    search_dirs=search_dirs, never_download=never_download)
  File "/home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules/virtualenv/virtualenv.py", line 571, in _install_req
    cwd=cwd)
  File "/home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules/virtualenv/virtualenv.py", line 1020, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/molecularecolo...us/python/bin/python -c "#!python
\"\"\"Bootstra...sys.argv[1:])






" /home/molecularecolo...ols-0.6c11-py2.7.egg failed with error code 1
Makefile:19: recipe for target 'virtPyRule' failed
make[1]: *** [virtPyRule] Error 1
make[1]: Leaving directory '/home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules'
Makefile:10: recipe for target 'all' failed
make: *** [all] Error 2
```
Thanks again for your help.

**Comment by fenderglass** [comment]
Strange, could you post the entire recipe file here?

As for cactus error - this is a known bug in Ubuntu-related distributions, here is a discussion with some fixes proposed: http://stackoverflow.com/questions/15608236/eclipse-and-google-app-engine-importerror-no-module-named-sysconfigdata-nd-u
