### ISSUE TITLE
AttributeError: 'Tree' object has not attribute 'identifier'

### ISSUE THREAD

**Issue by nickp60** [fenderglass/Ragout#24]
Hi,
I am trying to run the example E. coli dataset, and keep running into this issue.
```
23:37:35] INFO: Starting Ragout v2.0
[23:37:35] INFO: Synteny block scale set to 'small'
[23:37:35] INFO: Running Sibelia with block size 5000
[23:39:11] INFO: Running Sibelia with block size 500
[23:40:30] INFO: Running Sibelia with block size 100
[23:41:55] INFO: Inferring phylogeny from synteny blocks data
[23:41:55] DEBUG: Reading permutation file
[23:41:56] DEBUG: "mg1655" synteny blocks coverage: 99.57%
[23:41:56] DEBUG: "dh1" synteny blocks coverage: 99.87%
[23:41:56] DEBUG: Read 1 reference sequences
[23:41:56] DEBUG: Read 131 target sequences
[23:41:56] DEBUG: 131 target sequences left after indel filtering
[23:41:56] DEBUG: 79 target sequences left after repeat filtering
[23:41:56] DEBUG: Branch lengths: [1.5, 1.5], mu = 0.666666666667
[23:41:56] INFO: ('dh1' : 1.5, 'mg1655' : 1.5)
Traceback (most recent call last):
  File "/Users/nicholas/miniconda3/envs/ragout/bin/ragout.py", line 32, in <module>
    sys.exit(main())
  File "/Users/nicholas/miniconda3/envs/ragout/bin/ragout/main.py", line 286, in main
    _run_ragout(args)
  File "/Users/nicholas/miniconda3/envs/ragout/bin/ragout/main.py", line 176, in _run_ragout
    phylo_perm_file)
  File "/Users/nicholas/miniconda3/envs/ragout/bin/ragout/main.py", line 129, in _get_phylogeny_and_naming_ref
    leaves_sorted = phylogeny.leaves_by_distance(recipe["target"])
  File "/Users/nicholas/miniconda3/envs/ragout/bin/ragout/phylogeny/phylogeny.py", line 134, in leaves_by_distance
    rec_helper(self.tree)
  File "/Users/nicholas/miniconda3/envs/ragout/bin/ragout/phylogeny/phylogeny.py", line 126, in rec_helper
    if root.identifier == genome:
AttributeError: 'Tree' object has no attribute 'identifier'
```
Any tips for getting around this?  I have a hunch this has to do with how it is installed, (I have used ragout before and never seen this). but I don't know where to proceed...

Thanks in advance!

**Comment by fenderglass** [comment]
Hi,

This looks strange, never seen this kind of error either.. Do you happen to have "newick" python package installed in your system? Do the examples (from the corresponding folder) work for you?

**Comment by nickp60** [comment]
I am going to close this, as I think this would probably be best moved in the conda channels.  The issue seems to be due to different version of dependencies.  Thanks for your help!
