### ISSUE TITLE
Runtime error at phylogeny step

### ISSUE THREAD

**Issue by apredeus** [fenderglass/Ragout#31]
Hello, 

got the following error assembling one Salmonella genome against another reference one. Ragout version is the latest available via Bioconda. Any ideas how to debug this? Thanks!

```
[21:12:36] INFO: Starting Ragout v2.0
[21:12:36] INFO: Synteny block scale set to 'small'
[21:12:36] INFO: Running Sibelia with block size 5000
[21:13:16] INFO: Running Sibelia with block size 500
[21:13:55] INFO: Running Sibelia with block size 100
[21:14:36] INFO: Inferring phylogeny from synteny blocks data
[21:14:36] INFO: ('P125109' : 10.5, 'D24359' : 10.5)
Traceback (most recent call last):
  File "/pub37/alexp/miniconda2/bin/ragout.py", line 32, in <module>
    sys.exit(main())
  File "/pub37/alexp/miniconda2/bin/ragout/main.py", line 286, in main
    _run_ragout(args)
  File "/pub37/alexp/miniconda2/bin/ragout/main.py", line 176, in _run_ragout
    phylo_perm_file)
  File "/pub37/alexp/miniconda2/bin/ragout/main.py", line 129, in _get_phylogeny_and_naming_ref
    leaves_sorted = phylogeny.leaves_by_distance(recipe["target"])
  File "/pub37/alexp/miniconda2/bin/ragout/phylogeny/phylogeny.py", line 134, in leaves_by_distance
    rec_helper(self.tree)
  File "/pub37/alexp/miniconda2/bin/ragout/phylogeny/phylogeny.py", line 126, in rec_helper
    if root.identifier == genome:
AttributeError: 'Tree' object has no attribute 'identifier'
```

**Comment by fenderglass** [comment]
I updated the Bioconda version, should be working now. Thanks!
