### ISSUE TITLE
hal2maf : --start and --length require --refSequenceName

### ISSUE THREAD

**Issue by shameem356** [fenderglass/Ragout#46]
Hello @fenderglass 
I tried to run Ragout with hal option along with the example data which [you provided ](https://github.com/fenderglass/Ragout/issues/21). But I am getting the following hal error. Is it possible to run hal2maf with deafult value of --start and --length

**Command** : bin/ragout examples/hal_example/cholerae.rcp -o example_out --refine --overwrite -s hal ?
Error : 

10:58:31] INFO: Starting Ragout v2.2
[10:58:31] INFO: Running withs synteny block sizes '[5000, 500, 100]'
[10:58:31] INFO: Extracting FASTA from HAL
Warning: --inMemory is obsolete, use --hdf5InMemory
[10:58:31] INFO: Converting HAL to MAF
--start and --length require --refSequenceName

hal2maf v2.1: Convert hal database to maf.

USAGE:
hal2maf [Options] <halFile> <
mafFile> 

Traceback (most recent call last):
  File "/data/labs/genomics_lab/shared/apps/HAL/hal/bin/hal2mafMP.py", line 338, in <module>
    sys.exit(main())
  File "/data/labs/genomics_lab/shared/apps/HAL/hal/bin/hal2mafMP.py", line 335, in main
    runParallelSlices(args)
  File "/data/labs/genomics_lab/shared/apps/HAL/hal/bin/hal2mafMP.py", line 190, in runParallelSlices
    runParallelShellCommands(sliceCmds, options.numProc)
  File "/data/labs/genomics_lab/shared/apps/HAL/hal/stats/halStats.py", line 35, in runParallelShellCommands
    map(runShellCommand, cmdList)
  File "/data/labs/genomics_lab/shared/apps/HAL/hal/stats/halStats.py", line 28, in runShellCommand
    (command, sts))
RuntimeError: Command: hal2maf examples/hal_example/alignment.hal example_out/hal-workdir/alignment.maf --unique --noAncestors --refGenome h1 --start 0 --length 4041199 --targetGenomes o395,h1,inaba,biovar exited with non-zero status 1
Traceback (most recent call last):
  File "/data/labs/genomics_lab/shared/apps/Ragout/bin/ragout", line 32, in <module>
    sys.exit(main())
  File "/data/labs/genomics_lab/shared/apps/Ragout/ragout/main.py", line 290, in main
    _run_ragout(args)
  File "/data/labs/genomics_lab/shared/apps/Ragout/ragout/main.py", line 175, in _run_ragout
    args.threads)
  File "/data/labs/genomics_lab/shared/apps/Ragout/ragout/synteny_backend/synteny_backend.py", line 36, in make_permutations
    files = self.run_backend(recipe, output_dir, overwrite)
  File "/data/labs/genomics_lab/shared/apps/Ragout/ragout/synteny_backend/hal.py", line 103, in run_backend
    subprocess.check_call(cmdline, stdout=open(os.devnull, "w"))
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['hal2mafMP.py', 'examples/hal_example/alignment.hal', 'example_out/hal-workdir/alignment.maf', '--noAncestors', '--numProc', '1', '--refGenome', 'h1', '--targetGenomes', 'o395,h1,inaba,biovar']' returned non-zero exit status 1

**Comment by shameem356** [comment]
hello @fenderglass ,
Temporarily I removed **opt == 'start'  and opt == 'length'**  lines (line # 49 and 50) from   hal/bin/hal2mafMP.py and ragout worked fine. Please have a look into this for a permanent solution

**Comment by fenderglass** [comment]
Thank you. It looks like an error in the latest HAL revision (https://github.com/ComparativeGenomicsToolkit/hal/issues/88)

In the mean time, you can try to use the HAL github revision 276eb8c -  this is the one I used for my assemblies previously.

Hope this helps,
Mikhail

**Comment by shameem356** [comment]
thank you.
