### ISSUE TITLE
work flow stuck

### ISSUE THREAD

**Issue by mostafaabuzaid25** [fenderglass/Ragout#53]
I dont know what happen always stuck here.

> [20:33:39] INFO: Reading contigs file
[20:33:52] INFO: Detecting chimeric adjacencies
[20:35:05] INFO: Stage "10000"
[20:35:05] INFO: Removing chimeric adjacencies
[20:35:05] INFO: Inferring missing adjacencies
Traceback (most recent call last):
  File "/public/home/jmwu/soft/Ragout/bin/ragout", line 32, in <module>
    sys.exit(main())
  File "/public/home/jmwu/soft/Ragout/ragout/main.py", line 290, in main
    _run_ragout(args)
  File "/public/home/jmwu/soft/Ragout/ragout/main.py", line 214, in _run_ragout
    adjacencies = adj_inferer.infer_adjacencies()
  File "/public/home/jmwu/soft/Ragout/ragout/breakpoint_graph/inferer.py", line 44, in infer_adjacencies
    chosen_edges.extend(self._process_component(subgraph))
  File "/public/home/jmwu/soft/Ragout/ragout/breakpoint_graph/inferer.py", line 77, in _process_component
    adjacency = subgraph.to_weighted_graph(self.phylogeny)
  File "/public/home/jmwu/soft/Ragout/ragout/breakpoint_graph/breakpoint_graph.py", line 104, in to_weighted_graph
    g.add_nodes_from(self.bp_graph.nodes)
  File "/public/home/jmwu/miniconda2/lib/python2.7/site-packages/networkx/classes/graph.py", line 511, in add_nodes_from
    for n in nodes:
TypeError: 'instancemethod' object is not iterable

also with repeat algorithm

> [02:20:43] INFO: Starting Ragout v2.2

[02:20:44] INFO: Running withs synteny block sizes '[10000, 500, 100]'
[02:20:44] INFO: Extracting FASTA from HAL
[02:21:26] INFO: Converting HAL to MAF
[03:57:07] INFO: Extracting synteny blocks from MAF
[03:57:12] INFO: Running maf2synteny module
[04:00:28] INFO: Inferring phylogeny from synteny blocks data
[04:00:28] INFO: Reading /public/home/jmwu/ref2/Chilo_chr/hal-workdir/100/blocks_coords.txt
[04:00:32] INFO: "Trichoplusia" synteny blocks coverage: 13.71%
[04:00:33] INFO: "Chilo" synteny blocks coverage: 25.03%
[04:00:33] INFO: "Bomobyx" synteny blocks coverage: 12.87%
[04:00:33] WARNING: Some genomes have low synteny block coverage - results can be inaccurate. Possible reasons: 
	1. Genome is too distant from others
	2. Synteny block parameters are chosen incorrectly
	Try to change synteny blocks paramsters or remove this genome from the comparison
[04:00:44] INFO: Inferred tree: ('Bomobyx' : 2401.0, ('Chilo' : 1830.0, 'Trichoplusia' : 3906.0) : 2401.0)
[04:00:44] INFO: 'Trichoplusia' is chosen as a naming reference
[04:00:44] INFO: Processing permutation files
[04:00:44] INFO: Reading /public/home/jmwu/ref2/Chilo_chr/hal-workdir/10000/blocks_coords.txt
[04:00:44] INFO: "Trichoplusia" synteny blocks coverage: 29.8%
[04:00:44] INFO: "Chilo" synteny blocks coverage: 28.3%
[04:00:44] INFO: "Bomobyx" synteny blocks coverage: 31.03%
[04:00:44] WARNING: Some genomes have low synteny block coverage - results can be inaccurate. Possible reasons: 
	1. Genome is too distant from others
	2. Synteny block parameters are chosen incorrectly
	Try to change synteny blocks paramsters or remove this genome from the comparison
[04:00:44] INFO: Reading /public/home/jmwu/ref2/Chilo_chr/hal-workdir/500/blocks_coords.txt
[04:00:45] INFO: "Trichoplusia" synteny blocks coverage: 18.79%
[04:00:46] INFO: "Chilo" synteny blocks coverage: 27.37%
[04:00:46] INFO: "Bomobyx" synteny blocks coverage: 19.35%
[04:00:46] WARNING: Some genomes have low synteny block coverage - results can be inaccurate. Possible reasons: 
	1. Genome is too distant from others
	2. Synteny block parameters are chosen incorrectly
	Try to change synteny blocks paramsters or remove this genome from the comparison
[04:00:50] INFO: Reading /public/home/jmwu/ref2/Chilo_chr/hal-workdir/100/blocks_coords.txt
[04:00:54] INFO: "Trichoplusia" synteny blocks coverage: 13.71%
[04:00:54] INFO: "Chilo" synteny blocks coverage: 25.03%
[04:00:54] INFO: "Bomobyx" synteny blocks coverage: 12.87%
[04:00:54] WARNING: Some genomes have low synteny block coverage - results can be inaccurate. Possible reasons: 
	1. Genome is too distant from others
	2. Synteny block parameters are chosen incorrectly
	Try to change synteny blocks paramsters or remove this genome from the comparison
[04:01:07] INFO: Reading /public/home/jmwu/ref2/Chilo_chr/hal-workdir/100/blocks_coords.txt
[04:01:11] INFO: "Trichoplusia" synteny blocks coverage: 13.71%
[04:01:12] INFO: "Chilo" synteny blocks coverage: 25.03%
[04:01:12] INFO: "Bomobyx" synteny blocks coverage: 12.87%
[04:01:12] WARNING: Some genomes have low synteny block coverage - results can be inaccurate. Possible reasons: 
	1. Genome is too distant from others
	2. Synteny block parameters are chosen incorrectly
	Try to change synteny blocks paramsters or remove this genome from the comparison
[04:01:18] INFO: Resolving repeats
Traceback (most recent call last):
  File "/public/home/jmwu/soft/Ragout/bin/ragout", line 32, in <module>
    sys.exit(main())
  File "/public/home/jmwu/soft/Ragout/ragout/main.py", line 290, in main
    _run_ragout(args)
  File "/public/home/jmwu/soft/Ragout/ragout/main.py", line 191, in _run_ragout
    stage.ref_indels, phylogeny)
  File "/public/home/jmwu/soft/Ragout/ragout/breakpoint_graph/permutation.py", line 87, in __init__
    repeats, phylogeny, draft_names)
  File "/public/home/jmwu/soft/Ragout/ragout/breakpoint_graph/repeat_resolver.py", line 75, in resolve_repeats
    profiles = _split_into_profiles(by_genome, repeats, phylogeny)
  File "/public/home/jmwu/soft/Ragout/ragout/breakpoint_graph/repeat_resolver.py", line 180, in _split_into_profiles
    edges = _max_weight_matching(graph)
  File "/public/home/jmwu/soft/Ragout/ragout/breakpoint_graph/repeat_resolver.py", line 365, in _max_weight_matching
    for v1, v2 in edges:
ValueError: too many values to unpack

**Comment by fenderglass** [comment]
Hi,

It might be inconsistency between networkx package versions. I recommend to try the bioconda package.

Best,
Mikhail
