### ISSUE TITLE
Detecting chimeric adjacencies Error

### ISSUE THREAD

**Issue by sajjadasaf** [fenderglass/Ragout#72]
I run ragout but finished with following error.

[09:18:51] INFO: "punica" synteny blocks coverage: 75.03%
[09:18:51] INFO: "P1" synteny blocks coverage: 86.48%
[09:19:01] INFO: Reading contigs file
[09:19:06] INFO: Detecting chimeric adjacencies
Traceback (most recent call last):
  File "/home/sajjad/miniconda3/bin/ragout", line 33, in <module>
    sys.exit(load_entry_point('ragout==2.3', 'console_scripts', 'ragout')())
  File "/home/sajjad/miniconda3/lib/python3.7/site-packages/ragout/main.py", line 295, in main
    _run_ragout(args)
  File "/home/sajjad/miniconda3/lib/python3.7/site-packages/ragout/main.py", line 200, in _run_ragout
    chim_detect = ChimeraDetector(raw_bp_graphs, run_stages, target_sequences)
  File "/home/sajjad/miniconda3/lib/python3.7/site-packages/ragout/breakpoint_graph/chimera_detector.py", line 28, in __init__
    self._make_hierarchical_breaks()
  File "/home/sajjad/miniconda3/lib/python3.7/site-packages/ragout/breakpoint_graph/chimera_detector.py", line 64, in _make_hierarchical_breaks
    break_pos = self._optimal_break(seq_name, *adjusted_break)
  File "/home/sajjad/miniconda3/lib/python3.7/site-packages/ragout/breakpoint_graph/chimera_detector.py", line 72, in _optimal_break
    seq = self.target_seqs[seq_name]
KeyError: 'scafold596'

Here i attached  rcp and ragout.log files
[ragout.log](https://github.com/fenderglass/Ragout/files/5700509/ragout.log)
[P1 (copy)..txt](https://github.com/fenderglass/Ragout/files/5700513/P1.copy.txt)

**Comment by sajjadasaf** [comment]
Please please check it.

**Comment by fenderglass** [comment]
Probably you have changed the fasta headers in your contigs file into the form `genome.sequence` to generate .maf with SibeliaZ. You now need to supply the fasta file with original headers (before renaming) to run Ragout. Make sure that the header that gives you the KeyError exception is in the target fasta file.

Sorry for the confusion - SibeliaZ workflow is still experimental.
