### ISSUE TITLE
ERROR: UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b in position 1: ordinal not in range(128)

### ISSUE THREAD

**Issue by Wabanero** [fenderglass/Ragout#90]
I have my input files in the folder

```
(py27) *redacted*@pitys:~/test/Ragout$ ls -lah qsuber/
total 16G
4.0K Nov 22 11:09 .
4.0K Nov 22 10:55 ..
4.0K Nov 22 11:09 out
814M Nov 22 10:57 Qilex.fasta
818M Nov 22 10:57 Qlobata.fasta
763M Nov 22 10:57 Qrobur.fasta
714M Nov 22 10:57 Qrubra.fasta
734M Nov 22 10:57 Qsuber.fasta
12G Nov 22 11:02 quercus_subset.maf
226M Nov 22 10:57 Qvariabilis.fasta
502 Nov 22 11:09 recipe_suber.rcp
```

My recipe file is:

```
.references = Qvariabilis,Qlobata,Qilex,Qrobur,Qrubra
.target = Qsuber
.maf = quercus_subset.maf
#.tree = ((Qilex:0.210192,(Qsuber:0.105907,Qvariabilis:0.105907)N5:0.104285)N3:0.0375916,(Qrubra:0.230883,(Qlobata:0.112129,Qrobur:0.112129)N6:0.118754)N4:0.0169012);
Qvariabilis.fasta = Qvariabilis.fasta
Qlobata.fasta = Qlobata.fasta
Qilex.fasta = Qilex.fasta
Qrobur.fasta = Qrobur.fasta
Qrubra.fasta = Qrubra.fasta
Qsuber.fasta = Qsuber.fasta
```

I've succesfully run the example command for E.Coli
But if I launch my custom analysis using MAF input

`bin/ragout qsuber/recipe_suber.rcp --outdir qsuber/out/ --refine --debug`

This is the error I'm getting:

```
[11:37:48] INFO: Starting Ragout v2.3
[11:37:48] INFO: Running withs synteny block sizes '[10000, 500, 100]'
Traceback (most recent call last):
  File "bin/ragout", line 32, in <module>
    sys.exit(main())
  File "/home/fbergeretti/test/Ragout/ragout/main.py", line 295, in main
    _run_ragout(args)
  File "/home/fbergeretti/test/Ragout/ragout/main.py", line 177, in _run_ragout
    args.threads)
  File "/home/fbergeretti/test/Ragout/ragout/synteny_backend/synteny_backend.py", line 39, in make_permutations
    files = self.run_backend(recipe, output_dir, overwrite)
  File "/home/fbergeretti/test/Ragout/ragout/synteny_backend/sibelia.py", line 56, in run_backend
    chr2genome, total_size = _get_sequence_info(recipe)
  File "/home/fbergeretti/test/Ragout/ragout/synteny_backend/sibelia.py", line 110, in _get_sequence_info
    for line in f:
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b in position 1: ordinal not in range(128)
```

To be clear, software runs perfectly smooth in the py27 environment, using the example data.
But If I use my own data, plus the HAL to MAF alignment file obtained smoothly with cactus, it fails

Why is it running sybelia?

**Comment by mikolmogorov** [comment]
Sorry for my late response! You need to add `--synteny maf` to change the input type from Sibelia to Maf
